import Head from "next/head";
import Image from "next/image";
import AppBody from "../components/AppBody";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

export default function Home() {
	return (
		<div className="flex-grow overflow-y-hidden">
			<Head>
				<title>Gmail</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<AppBody />
		</div>
	);
}
